services:
  - type: web
    name: socket-server
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node server.js'
    envVars:
      - key: NODE_ENV
        value: production
      - key: SOCKET_SERVER_URL
        value: https://your-render-app-name.onrender.com
      - key: PORT
        value: 4000
